export const USER_LOGIN = 'USER_LOGIN'  //登录
export const USER_REGIST = 'USER_REGIST' //注册
export const USER_LOGOUT = 'USER_LOGOUT' // 注销
export const Menu_SELECT = 'Menu_SELECT' //选择菜单
export const FOLLOW_SELECT = 'FOLLOW_SELECT' //关注 粉丝
export const SPIN_SHOW = 'SPIN_SHOW' //spin加载是否显示
export const REGIST_SHOW = 'REGIST_SHOW' //注册Modal显示
export const LOGIN_SHOW = 'LOGIN_SHOW' //注册Modal显示
export const USER_INFO = 'USER_INFO' //设置用户信息